### ISSUE TITLE
Stopped working after upgrade to 1.0 from 0.9

### ISSUE THREAD

**Issue by tonymk** [soates/Auto-Import#10]
Hi!
First of all lover your extension!

But it stopped working after I upgraded from 0.9 to 1.0, 
it does not give any suggestions for imports("No fix suggestion").

I'm on windows 10, vscode 1.6.0-insider.
angular-cli": "1.0.0-beta.14,
angular 2.0.0
typescript 2.0.2

does not work with default new angular2-cli new project, 

while at it, a feature request: sorting of imports, maybe after config? 

Cheers

**Comment by dandevs** [comment]
Same problem here on vscode 1.5.2 on Windows. None of the discovered symbols come up on autocomplete, no auto import.

**Comment by soates** [comment]
Hi guys, really sorry for this one - it was quite a pain to actually track down.

it should now be fixed in 1.0.1

Thanks for reporting it guys :)
