### ISSUE TITLE
Ignore comments

### ISSUE THREAD

**Issue by caseyhoward** [soates/Auto-Import#4]
```js
// import {Widget} from './widget';
new Widget();
```

If I import Widget it is added to the comment like so:
```js
// import {Widget, Widget} from './widget';
new Widget();
```

Also, may this should be another issue, but the using of existing imports is awkward in general.

```js
import './widget';
new Widget
```

If I try to import Widget, nothing happens.

**Comment by soates** [comment]
Ill look at adding this ASAP.

**Comment by zhaoshengjun** [comment]
Just created a PR for this.
