### ISSUE TITLE
Importing var from module

### ISSUE THREAD

**Issue by 19majkel94** [soates/Auto-Import#5]
This extension works great with classes - it finds file with class in project and makes correct imports.
But I have a few files where I have exported not only a class but also a var - it can't find it and don't provide quick-fix for import it:

    export class User extends Document<User> {
        ...
    }
    export var userModel: mongoose.Model<User> = defineSchema<User>(User);

It's a bug or you just don't support var export?

**Comment by soates** [comment]
ah, your right.

you could use export let instead - which would work!

**Comment by soates** [comment]
Added var support in 0.9
