### ISSUE TITLE
Exported enums are not detected by Auto-Import

### ISSUE THREAD

**Issue by RPDeshaies** [soates/Auto-Import#52]
If I export a class, Auto-Import is able to detect it.
But if I export an enum, it only detects the class.

![image](https://cloud.githubusercontent.com/assets/6224111/22759131/4faceb54-ee1f-11e6-82e5-5aee6d26297d.png)
![image](https://cloud.githubusercontent.com/assets/6224111/22759141/54d37b7a-ee1f-11e6-90b4-21a8c5819829.png)

If I remove the class

![image](https://cloud.githubusercontent.com/assets/6224111/22759150/60ba2d9e-ee1f-11e6-919d-27ccd1f04350.png)
![image](https://cloud.githubusercontent.com/assets/6224111/22759159/6491168a-ee1f-11e6-8c97-889b0a3f7ad3.png)

**Comment by soates** [comment]
Done
