### ISSUE TITLE
Maintenance the extension

### ISSUE THREAD

**Issue by martinoppitz** [soates/Auto-Import#57]
How can we maintenance this project?

**Comment by lukeautry** [comment]
@martinoppitz @soates I would consider this extension to be obsolete now that vscode/typescript support auto-import quick fix now.,

There would possible be some value if you were locked into a TypeScript version earlier than 2.2, but I don't know how common or important that case is.

**Comment by martinoppitz** [comment]
Look at JavaScript

**Comment by giniedp** [comment]
i wouldnt say its obsolete. The plugin suggests an autoimport while typing. vscode/typescript does not. At least not yet.

**Comment by soates** [comment]
@martinoppitz Feel free to fork and republish

**Comment by soates** [comment]
I will be working on this again.
