### ISSUE TITLE
filesToScan glob not used for watching files

### ISSUE THREAD

**Issue by samuelmaddock** [soates/Auto-Import#6]
The setting is read, but never used in [this section of the code](https://github.com/soates/Auto-Import/blob/7d26d9ee6c87a58c9d6ab198f4cc6fa7bafdb37b/src/auto-import.ts#L50-L54).

**Comment by soates** [comment]
Good eyes, I have just noticed that one my self - fixed in 0.9 which I will be releasing tonight :)
