### ISSUE TITLE
Provide option to set default position to import

### ISSUE THREAD

**Issue by DerekTso** [soates/Auto-Import#60]
It imports the file path **at the first line** of the files right now.

It will be better if there's an option to set default position to import.

Let's say to import the file path **at the end** of the import list, by default.

**Comment by zaha** [comment]
Came here to suggest the same :)

**Comment by dalemanthei** [comment]
Our use case is that the first lines of our files are a standard copyright some 20+ lines long. Our linter checks that the imports are in lexical order and is capable of fixing some of the errors .. as long as the imports are all together. So inserting the new import before the first existing import or after the last one works for me.

**Comment by shobhitg** [comment]
I would like to request that there should be another option to import in some kind of sorted position. Sorting could be based on the name of the file we are importing. Git diffs would be much nicer that way.

**Comment by leocaseiro** [comment]
I apologise for mentioning another extension, but the TypeScript Hero uses some KeyWords to organize the imports. 

> From their docs
>
> Keyword imports
> `Modules` : contains all imports from modules (npm etc) `import ... from 'vscode';`
> `Plains` : contains all string only imports `import 'reflect-metadata;`
> `Workspace` : contains all local project files `import ... from '../server';`
> `Remaining` : contains all imports that are not matched by other import groups


It's a good idea and it might help to implement that for ES6 within this extension.

The PR: https://github.com/buehler/typescript-hero/pull/195

How to use it https://github.com/buehler/typescript-hero/issues/278
