### ISSUE TITLE
Auto-Import does not work for multi-root workspace

### ISSUE THREAD

**Issue by marcelh-gh** [soates/Auto-Import#84]
Hi,
are there any prerequisites?
Even in a super simple new multi-root workspace with just two files in two root folders (one export, the other with the supposed import) it does not work for me.
Cheers,
Marcel

**Comment by marcelh-gh** [comment]
TypeScript 2.7.2
VS Code 1.21.0
Auto-Import 1.5.3

**Comment by marcelh-gh** [comment]
@soates Hi, my assumption is that _'multi-root workspace'_ ready means that Auto-Import searches for imports in all root folders of a workspace. Is that correct? Thanks, Marcel

**Comment by alphacat2018** [comment]
@marcelh-gh hey, I have exactly the same problem here. Have you found the solution? Thanks.
