### ISSUE TITLE
Annoying popup about autoimport cache

### ISSUE THREAD

**Issue by 19majkel94** [soates/Auto-Import#9]
Is there an config option which allow to disable annoying notification about autoimport cache has been build?

Maybe you could move this info to statusbar on bottom like other extensions?

**Comment by soates** [comment]
Try using the showNotifications option mate, that should hide them - you will need to restart your window after it :)

**Comment by 19majkel94** [comment]
I thought this is setting for a QuickFix lightbulb :laughing:
