### ISSUE TITLE
Unknown section in status bar

### ISSUE THREAD

**Issue by pingshunhuangalex** [soates/Auto-Import#91]
I just installed the extension and I noticed it adds an extra section in my status bar. I have no idea what it does and just wondering if there is a way to turn this thing off cuz space in the status bar is very precious. Thanks.

![capture](https://user-images.githubusercontent.com/17170199/42484958-d0249718-8438-11e8-8437-7949601f834d.PNG)

**Comment by SolarLiner** [comment]
Same here. I couldn't find any documentation on it (in fact I couldn't find any documentation *at all*). I would love to know what it means because it just uses space for nothing and isn't even clickable. Thanks!
